language: cpp

git:
  depth: 1

os:
  - linux
# - osx

branches:
  only:
    - master
    - devel

compiler:
  - gcc

matrix:
  include:
    - os: linux
      env:
        - BUILD="qmake"
  fast_finish: true
#    - os: osx
#      osx_image: xcode8.3
#      env:
#        - MATRIX_EVAL="brew update"

#  GMIC blessed repo has been moved to Framagit (June 2018)
#  - git clone --depth=1 https://github.com/dtschump/gmic.git gmic-clone

before_install:
  - date -u
  - uname -a
  - git clone --depth=1 https://framagit.org/dtschump/gmic.git gmic
  - make -C gmic/src CImg.h gmic_stdlib.h

install:
  - if [ -z "$TRAVIS_OS_NAME" -o "$TRAVIS_OS_NAME" = "linux" ]; then
       sudo apt-get install gdb libfftw3-dev zlib1g-dev libcurl4-openssl-dev libx11-dev libgimp2.0-dev qt5-default qt5-qmake qtbase5-dev qttools5-dev;
    fi;

script:
  - g++ --version
  - if [ -z "$TRAVIS_OS_NAME" -o "$TRAVIS_OS_NAME" = "linux" ]; then
       travis_wait 45 ./scripts/travis_build_${BUILD}.sh;
    fi;
